# Action whitelist/blacklist configuration
action-list:
  whitelist:
    - actions/checkout@*
    - actions/setup-node@*
    - actions/cache@*
    - hashicorp/*@*
  blacklist:
    - untrusted/*@*
    - suspicious/*@*
