# Action whitelist/blacklist configuration
action-list:
    - actions/*@*
    - docker/build-push-action@*
    - reviewdog/action-setup@*
    - goreleaser/goreleaser-action@*
    - github/codeql-action/*@*
