version: "2"
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  default: none
  enable:
    - copyloopvar
    - decorder
    - errcheck
    - errname
    - errorlint
    - goconst
    - govet
    - ineffassign
    - loggercheck
    - makezero
    - misspell
    - nilerr
    - noctx
    - prealloc
    - reassign
    - staticcheck
    - tparallel
    - unconvert
    - unused
    - usestdlibvars
    - usetesting
    - whitespace
  settings:
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
