# This workflow demonstrates heuristic detection for unknown third-party artifact actions
# The rule should detect any action with "download" and "artifact" in its name
#
# VULNERABILITY: Unknown third-party artifact download action is used with
# pull_request_target trigger without specifying a safe extraction path.
#
# Expected sisakulint detection:
# - artifact-poisoning-medium rule should flag this workflow using heuristic detection

name: Heuristic Detection - Artifact Poisoning Medium

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # VULNERABLE: Generic "download-artifact" action (not in known list)
      # Should be detected by heuristic pattern matching
      - uses: some-org/download-artifact-action@v1
        with:
          artifact-name: build-output

      # VULNERABLE: Another variation with different naming
      - uses: custom/artifact-download@main
        with:
          name: test-results

      - name: Process artifacts
        run: |
          echo "Processing artifacts..."
