# This workflow demonstrates a vulnerable pattern for artifact poisoning (medium severity)
# Based on: https://codeql.github.com/codeql-query-help/actions/actions-artifact-poisoning-medium/#example
#
# VULNERABILITY: Third-party artifact download action (dawidd6/action-download-artifact)
# is used with workflow_run trigger without specifying a safe extraction path.
# This may allow malicious artifacts to overwrite existing files.
#
# Expected sisakulint detection:
# - artifact-poisoning-medium rule should flag this workflow

name: Insecure Workflow - Artifact Poisoning Medium

on:
  workflow_run:
    workflows: ["Prev"]
    types:
      - completed

jobs:
  Download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # VULNERABLE: No path specified for third-party artifact download action
      # Artifacts are extracted to workspace root by default, allowing file overwrites
      - uses: dawidd6/action-download-artifact@v2
        with:
          name: pr_number

      # DANGER: Executing scripts from downloaded artifacts without validation
      - name: Run command
        run: |
          sh cmd.sh
