# This workflow demonstrates a safe pattern for artifact handling
# Based on: https://codeql.github.com/codeql-query-help/actions/actions-artifact-poisoning-medium/#example
#
# SECURE: Third-party artifact download action extracts to a safe temporary location
# using ${{ runner.temp }}/artifacts/, preventing file overwrites in the workspace.
#
# Expected sisakulint detection:
# - No errors should be reported for this workflow

name: Secure Workflow - Artifact Poisoning Medium

on:
  workflow_run:
    workflows: ["Prev"]
    types:
      - completed

jobs:
  Download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Ensure artifacts directory exists
      - run: mkdir -p ${{ runner.temp }}/artifacts/

      # SECURE: Explicitly specify safe extraction path using runner.temp
      # This prevents malicious artifacts from overwriting workspace files
      - uses: dawidd6/action-download-artifact@v2
        with:
          name: pr_number
          path: ${{ runner.temp }}/artifacts/

      # Best practice: Validate artifact content before use
      # (checksums, signatures, etc.)
      - name: Run command
        run: |
          sh cmd.sh
