# Safe workflow for testing cache-poisoning-poisonable-step rule
# Based on CodeQL example: https://codeql.github.com/codeql-query-help/actions/actions-cache-poisoning-poisonable-step/
name: Secure Workflow

on:
  pull_request:
    branches: [main]

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run tests
        run: ./run_tests.sh
