# Vulnerable workflow for testing cache-poisoning-poisonable-step rule
# This workflow runs untrusted code after checking out PR head code
# Based on CodeQL example: https://codeql.github.com/codeql-query-help/actions/actions-cache-poisoning-poisonable-step/
name: Vulnerable Workflow
on:
  pull_request_target:
    branches: [main]
permissions: {}
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        timeout-minutes: 5
      - name: Run tests
        timeout-minutes: 5
        run: ./run_tests.sh
