# Vulnerable workflow for testing cache-poisoning-poisonable-step rule
# This workflow runs untrusted code after checking out PR head code
# Based on CodeQL example: https://codeql.github.com/codeql-query-help/actions/actions-cache-poisoning-poisonable-step/
name: Vulnerable Workflow

on:
  pull_request_target:
    branches: [main]

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run tests
        run: ./run_tests.sh
