name: Code Injection Critical - Privileged Triggers
on:
  # Privileged triggers that have write access or secrets
  pull_request_target:
    types: [opened, synchronize]
  workflow_run:
    workflows: ["CI"]
    types: [completed]
  issue_comment:
    types: [created]

jobs:
  # CRITICAL: Untrusted input with privileged trigger (pull_request_target)
  unsafe-pr-target:
    runs-on: ubuntu-latest
    steps:
      - name: Echo PR title
        run: echo "${{ github.event.pull_request.title }}"

  # CRITICAL: Untrusted input with workflow_run trigger
  unsafe-workflow-run:
    runs-on: ubuntu-latest
    steps:
      - name: Process results
        run: |
          echo "Head ref: ${{ github.event.workflow_run.head_branch }}"

  # CRITICAL: Untrusted input with issue_comment trigger
  unsafe-issue-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Process comment
        run: echo "${{ github.event.comment.body }}"

  # CRITICAL: github-script with privileged trigger
  unsafe-github-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            console.log('Comment: ${{ github.event.comment.body }}')

  # SAFE: Using environment variables in privileged context
  safe-with-env:
    runs-on: ubuntu-latest
    steps:
      - name: Echo PR title safely
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: echo "$PR_TITLE"

  # SAFE: github-script with env variables
  safe-github-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
        with:
          script: |
            const { COMMENT_BODY } = process.env
            console.log('Comment:', COMMENT_BODY)
