name: Code Injection in GitHub Script
on:
  issue_comment:
    types: [created]

jobs:
  # UNSAFE: Direct use of untrusted input in github-script
  unsafe-github-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            console.log('Comment: ${{ github.event.comment.body }}')
            const title = '${{ github.event.issue.title }}'
            console.log(title)

  # SAFE: Using environment variables with github-script
  safe-github-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
        with:
          script: |
            const { COMMENT_BODY, ISSUE_TITLE } = process.env
            console.log('Comment:', COMMENT_BODY)
            console.log('Title:', ISSUE_TITLE)

  # UNSAFE: Mixed - some untrusted inputs not in env
  mixed-github-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
        with:
          script: |
            const { COMMENT_BODY } = process.env
            console.log('Comment:', COMMENT_BODY)
            // This is unsafe - not in env
            const title = '${{ github.event.issue.title }}'
            console.log('Title:', title)
