name: Code Injection Medium - Normal Triggers
on:
  # Normal triggers with limited permissions
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

jobs:
  # MEDIUM: Untrusted input with normal trigger (pull_request)
  unsafe-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Echo PR title
        run: echo "${{ github.event.pull_request.title }}"

  # MEDIUM: Multiple untrusted inputs
  unsafe-multiple:
    runs-on: ubuntu-latest
    steps:
      - name: Process PR data
        run: |
          echo "Title: ${{ github.event.pull_request.title }}"
          echo "Body: ${{ github.event.pull_request.body }}"
          echo "Head ref: ${{ github.event.pull_request.head.ref }}"

  # MEDIUM: github-script with normal trigger
  unsafe-github-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const title = '${{ github.event.pull_request.title }}'
            console.log(title)

  # SAFE: Using environment variables
  safe-with-env:
    runs-on: ubuntu-latest
    steps:
      - name: Echo PR title safely
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: echo "$PR_TITLE"

  # SAFE: Trusted inputs (no untrusted context)
  safe-trusted:
    runs-on: ubuntu-latest
    steps:
      - name: Echo commit SHA
        run: echo "${{ github.sha }}"

      - name: Echo repository name
        run: echo "${{ github.repository }}"
