name: PATH Injection Critical - Privileged Triggers
on:
  # Privileged triggers that have write access or secrets
  pull_request_target:
    types: [opened, synchronize]
  workflow_run:
    workflows: ["CI"]
    types: [completed]
  issue_comment:
    types: [created]

jobs:
  # CRITICAL: Untrusted input written to GITHUB_PATH with privileged trigger
  unsafe-pr-target:
    runs-on: ubuntu-latest
    steps:
      - name: Set PATH from PR body
        run: |
          echo "${{ github.event.pull_request.body }}" >> "$GITHUB_PATH"

      - name: Use the PATH
        run: 'echo "PATH updated"'

  # CRITICAL: Multiple untrusted inputs in GITHUB_PATH
  unsafe-multiple-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Set multiple paths
        run: |
          echo "${{ github.event.pull_request.title }}" >> $GITHUB_PATH
          echo "${{ github.event.pull_request.body }}" >> $GITHUB_PATH
          echo "${{ github.event.comment.body }}" >> $GITHUB_PATH

  # CRITICAL: Untrusted input in workflow_run trigger
  unsafe-workflow-run:
    runs-on: ubuntu-latest
    steps:
      - name: Set PATH from workflow run
        run: |
          echo "${{ github.event.workflow_run.head_branch }}" >> "$GITHUB_PATH"

  # CRITICAL: Extracted path from untrusted input
  unsafe-extracted-path:
    runs-on: ubuntu-latest
    steps:
      - name: Extract and set PATH
        run: |
          PATH_VALUE=$(echo "${{ github.event.comment.body }}" | grep -oP 'system path: \K\S+')
          echo "$PATH_VALUE" >> "$GITHUB_PATH"

  # SAFE: Using realpath to validate the path
  safe-with-realpath:
    runs-on: ubuntu-latest
    steps:
      - name: Set PATH safely with realpath
        env:
          USER_PATH: ${{ github.event.pull_request.body }}
        run: |
          VALIDATED_PATH=$(realpath "$USER_PATH")
          echo "$VALIDATED_PATH" >> "$GITHUB_PATH"

  # SAFE: Using environment variable as intermediary with validation
  safe-with-env-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Set PATH with validation
        env:
          USER_PATH: ${{ github.event.pull_request.body }}
        run: |
          # Validate the path exists and is a directory
          if [ -d "$USER_PATH" ]; then
            echo "$USER_PATH" >> "$GITHUB_PATH"
          fi

  # SAFE: Not using untrusted input
  safe-trusted-only:
    runs-on: ubuntu-latest
    steps:
      - name: Set PATH from trusted sources
        run: |
          echo "/usr/local/bin" >> "$GITHUB_PATH"
          echo "${{ github.workspace }}/bin" >> "$GITHUB_PATH"

  # SAFE: Using hardcoded paths
  safe-hardcoded:
    runs-on: ubuntu-latest
    steps:
      - name: Set known PATH
        run: |
          echo "/opt/tools/bin" >> "$GITHUB_PATH"
