name: Environment Variable Injection Critical - Privileged Triggers
on:
  # Privileged triggers that have write access or secrets
  pull_request_target:
    types: [opened, synchronize]
  workflow_run:
    workflows: ["CI"]
    types: [completed]
  issue_comment:
    types: [created]

jobs:
  # CRITICAL: Untrusted input written to GITHUB_ENV with privileged trigger
  unsafe-pr-target:
    runs-on: ubuntu-latest
    steps:
      - name: Set env from PR title
        run: |
          echo "PR_TITLE=${{ github.event.pull_request.title }}" >> "$GITHUB_ENV"

      - name: Use the env var
        run: 'echo "Title: $PR_TITLE"'

  # CRITICAL: Multiple untrusted inputs in GITHUB_ENV
  unsafe-multiple-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Set multiple env vars
        run: |
          echo "PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV
          echo "PR_BODY=${{ github.event.pull_request.body }}" >> $GITHUB_ENV
          echo "COMMENT=${{ github.event.comment.body }}" >> $GITHUB_ENV

  # CRITICAL: Untrusted input in workflow_run trigger
  unsafe-workflow-run:
    runs-on: ubuntu-latest
    steps:
      - name: Set env from workflow run
        run: |
          echo "HEAD_BRANCH=${{ github.event.workflow_run.head_branch }}" >> "$GITHUB_ENV"

  # CRITICAL: Complex expression with untrusted data
  unsafe-complex-expr:
    runs-on: ubuntu-latest
    steps:
      - name: Set env with processing
        run: |
          REPLACED=$(echo "${{ github.event.pull_request.title }}" | sed 's/foo/bar/g')
          echo "PROCESSED=$REPLACED" >> "$GITHUB_ENV"

  # SAFE: Using tr -d '\n' to remove newlines
  safe-with-tr:
    runs-on: ubuntu-latest
    steps:
      - name: Set env safely with tr
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "PR_TITLE=$(echo "$PR_TITLE" | tr -d '\n')" >> "$GITHUB_ENV"

  # SAFE: Using heredoc with unique delimiter
  safe-with-heredoc:
    runs-on: ubuntu-latest
    steps:
      - name: Set multiline env safely
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          EOF_MARKER="EOF_$(uuidgen)"
          {
            echo "PR_BODY<<$EOF_MARKER"
            echo "$PR_BODY"
            echo "$EOF_MARKER"
          } >> "$GITHUB_ENV"

  # SAFE: Not writing untrusted data to GITHUB_ENV
  safe-no-github-env:
    runs-on: ubuntu-latest
    steps:
      - name: Use env directly
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "Title: $PR_TITLE"

  # SAFE: Using trusted input (github.sha, github.ref)
  safe-trusted-input:
    runs-on: ubuntu-latest
    steps:
      - name: Set env from trusted sources
        run: |
          echo "SHA=${{ github.sha }}" >> "$GITHUB_ENV"
          echo "REF=${{ github.ref }}" >> "$GITHUB_ENV"
