# Safe: Proper Access Control
# This workflow is safe because:
# 1. It uses 'labeled' event type which only triggers when a label is added
# 2. It uses immutable 'head.sha' instead of mutable 'head.ref'
#
# This prevents the attack scenario where code changes after label approval
#
# Reference: https://codeql.github.com/codeql-query-help/actions/actions-improper-access-control/

name: Proper Access Control - Safe
on:
  pull_request_target:
    types: [labeled]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # Safe: Uses 'labeled' event and immutable SHA
      - name: Checkout PR code
        uses: actions/checkout@v4
        if: contains(github.event.pull_request.labels.*.name, 'safe to test')
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run tests
        run: |
          npm install
          npm test

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # Safe: immutable SHA reference
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Build
        run: make build

  # Alternative safe pattern: no checkout of PR code at all
  lint-metadata:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # Safe: Default checkout (base branch, not PR code)
      - name: Checkout base
        uses: actions/checkout@v4

      - name: Check PR metadata
        run: |
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "PR Author: ${{ github.event.pull_request.user.login }}"
