# Vulnerable: Improper Access Control
# This workflow is vulnerable because:
# 1. It uses 'synchronize' event type which allows code changes after label approval
# 2. It uses mutable 'head.ref' instead of immutable 'head.sha'
#
# Attack scenario:
# 1. Attacker opens a PR with benign code
# 2. Maintainer reviews and adds "safe to test" label
# 3. Attacker pushes malicious code (synchronize event triggers)
# 4. Workflow runs with malicious code using the previously approved label
#
# Reference: https://codeql.github.com/codeql-query-help/actions/actions-improper-access-control/

name: Improper Access Control - Vulnerable
on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # Vulnerable: Uses label check but allows synchronize and uses mutable ref
      - name: Checkout PR code
        uses: actions/checkout@v4
        if: contains(github.event.pull_request.labels.*.name, 'safe to test')
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Run tests
        run: |
          npm install
          npm test

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # Also vulnerable: mutable ref without label check
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Build
        run: make build

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # Also vulnerable: uses github.head_ref which is mutable
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Deploy
        run: ./deploy.sh
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
