name: All Untrusted Inputs Test
on:
  push:
  pull_request:
  issue_comment:
  issues:
  discussion:
  discussion_comment:

jobs:
  # github.event.issue.title / github.event.issue.body
  issue-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.issue.title }}"
      - run: echo "${{ github.event.issue.body }}"

  # github.event.pull_request.title / body / head.*
  pull-request-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.pull_request.title }}"
      - run: echo "${{ github.event.pull_request.body }}"
      - run: echo "${{ github.event.pull_request.head.ref }}"
      - run: echo "${{ github.event.pull_request.head.label }}"
      - run: echo "${{ github.event.pull_request.head.sha }}"
      - run: echo "${{ github.event.pull_request.head.repo.default_branch }}"

  # github.event.comment.body
  comment-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.comment.body }}"

  # github.event.review.body
  review-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.review.body }}"

  # github.event.review_comment.body
  review-comment-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.review_comment.body }}"

  # github.event.pages.*.page_name (array access)
  pages-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.pages[0].page_name }}"

  # github.event.commits.*.message / author.email / author.name
  commits-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.commits[0].message }}"
      - run: echo "${{ github.event.commits[0].author.email }}"
      - run: echo "${{ github.event.commits[0].author.name }}"

  # github.event.head_commit.message / author.email / author.name
  head-commit-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.head_commit.message }}"
      - run: echo "${{ github.event.head_commit.author.email }}"
      - run: echo "${{ github.event.head_commit.author.name }}"

  # github.event.discussion.title / body
  discussion-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.discussion.title }}"
      - run: echo "${{ github.event.discussion.body }}"

  # github.head_ref
  head-ref-input:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.head_ref }}"

# Expected: All 21 inputs should be detected as untrusted
# 1. github.event.issue.title
# 2. github.event.issue.body
# 3. github.event.pull_request.title
# 4. github.event.pull_request.body
# 5. github.event.pull_request.head.ref
# 6. github.event.pull_request.head.label
# 7. github.event.pull_request.head.sha
# 8. github.event.pull_request.head.repo.default_branch
# 9. github.event.comment.body
# 10. github.event.review.body
# 11. github.event.review_comment.body
# 12. github.event.pages[0].page_name
# 13. github.event.commits[0].message
# 14. github.event.commits[0].author.email
# 15. github.event.commits[0].author.name
# 16. github.event.head_commit.message
# 17. github.event.head_commit.author.email
# 18. github.event.head_commit.author.name
# 19. github.event.discussion.title
# 20. github.event.discussion.body
# 21. github.head_ref
