name: Issue Injection Edge Cases
on:
  pull_request:
    types: [opened, edited]
  issue_comment:
    types: [created]

jobs:
  # Case 1: Single line untrusted input (UNSAFE)
  unsafe-single-line:
    runs-on: ubuntu-latest
    steps:
      - name: Echo PR title directly
        run: echo "${{ github.event.pull_request.title }}"

  # Case 2: Multiline expression (UNSAFE)
  unsafe-multiline:
    runs-on: ubuntu-latest
    steps:
      - name: Multiline expression
        run: |
          echo "${{
            github.event.pull_request.title
          }}"

  # Case 3: Safe pattern using environment variable
  safe-env-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Safe echo via env
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: echo "$PR_TITLE"

  # Case 4: Trusted input (github.sha is safe)
  safe-trusted-input:
    runs-on: ubuntu-latest
    steps:
      - name: Echo commit SHA
        run: echo "${{ github.sha }}"

  # Case 5: Multiple untrusted inputs in multiline script (UNSAFE)
  unsafe-multiple-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Multiple untrusted inputs
        run: |
          echo "Title: ${{ github.event.pull_request.title }}"
          echo "Body: ${{ github.event.pull_request.body }}"
          echo "Comment: ${{ github.event.comment.body }}"

  # Case 6: Multiline expression with fallback (UNSAFE)
  unsafe-multiline-fallback:
    runs-on: ubuntu-latest
    steps:
      - name: Multiline with fallback
        run: |
          echo "${{
            github.event.pull_request.title ||
            github.event.issue.title
          }}"

  # Case 7: Mixed safe and unsafe in same job
  mixed-patterns:
    runs-on: ubuntu-latest
    steps:
      - name: Safe step with env
        env:
          LABEL: ${{ github.event.pull_request.head.label }}
        run: echo "$LABEL"

      - name: Unsafe step without env
        run: echo "${{ github.event.pull_request.head.ref }}"

  # Case 8: Nested expression in complex script (UNSAFE)
  unsafe-complex-script:
    runs-on: ubuntu-latest
    steps:
      - name: Complex multiline script
        run: |
          set -e
          TITLE="${{
            github.event.pull_request.title
          }}"
          if [[ "$TITLE" == *"feat"* ]]; then
            echo "Feature detected"
          fi

# Expected detections:
# - unsafe-single-line: github.event.pull_request.title
# - unsafe-multiline: github.event.pull_request.title
# - unsafe-multiple-inputs: title, body, comment.body
# - unsafe-multiline-fallback: title, issue.title
# - mixed-patterns (step 2): head.ref
# - unsafe-complex-script: title
#
# Safe patterns (no detection):
# - safe-env-variable: uses env intermediary
# - safe-trusted-input: github.sha is trusted
# - mixed-patterns (step 1): uses env intermediary
