# Vulnerable workflow demonstrating secrets-in-artifacts issues
# This file contains examples that should trigger the secrets-in-artifacts rule
# Based on CodeQL rule: https://codeql.github.com/codeql-query-help/actions/actions-secrets-in-artifacts/
# CWE-312: Cleartext Storage of Sensitive Information

name: secrets-in-artifacts-vulnerable
on: pull_request

jobs:
  # NOTE: path: . with v4 is SAFE because v4 excludes hidden files by default
  # The following examples show ACTUAL vulnerabilities

  vulnerable-old-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # VULNERABLE: v3 includes hidden files by default
      # Even with a specific path, .git-related files in that directory are uploaded
      - name: Upload with old version
        uses: actions/upload-artifact@v3
        with:
          name: old-version-artifact
          path: dist/

  # NOTE: path: "**" with v4 is SAFE because v4 excludes hidden files by default

  vulnerable-hidden-files-enabled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # VULNERABLE: Explicitly enabling hidden files with path: . is dangerous
      - name: Upload with hidden files enabled
        uses: actions/upload-artifact@v4
        with:
          name: hidden-files-artifact
          path: .
          include-hidden-files: true

  vulnerable-sensitive-path:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # VULNERABLE: Directly uploading sensitive files
      - name: Upload .env file
        uses: actions/upload-artifact@v4
        with:
          name: env-artifact
          path: .env

  vulnerable-git-directory:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # VULNERABLE: Uploading .git directory directly
      - name: Upload .git directory
        uses: actions/upload-artifact@v4
        with:
          name: git-artifact
          path: .git
