# This workflow demonstrates safe secret handling patterns
# These patterns should NOT be flagged by the secret-exposure rule
name: Safe Secret Handling

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'

jobs:
  # SAFE: Using specific secret references with dot notation
  safe-specific-secrets:
    runs-on: ubuntu-latest
    env:
      # GOOD: Explicit secret reference
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # GOOD: Another explicit secret reference
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Use secrets safely
        run: |
          echo "Using GITHUB_TOKEN for authentication"
          echo "Using NPM_TOKEN for publishing"

  # SAFE: Using conditional logic instead of dynamic access
  conditional-secret-access:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev, staging, prod]
    steps:
      # GOOD: Use conditional logic to select specific secrets
      - name: Get dev token
        if: matrix.env == 'dev'
        env:
          TOKEN: ${{ secrets.GH_PAT_DEV }}
        run: echo "Using dev token"

      - name: Get staging token
        if: matrix.env == 'staging'
        env:
          TOKEN: ${{ secrets.GH_PAT_STAGING }}
        run: echo "Using staging token"

      - name: Get prod token
        if: matrix.env == 'prod'
        env:
          TOKEN: ${{ secrets.GH_PAT_PROD }}
        run: echo "Using prod token"

  # SAFE: Using toJSON with non-secret variables
  safe-tojson-usage:
    runs-on: ubuntu-latest
    steps:
      - name: Debug matrix values
        env:
          # GOOD: toJSON with matrix (not secrets)
          MATRIX_JSON: ${{ toJSON(matrix) }}
        run: echo "Matrix $MATRIX_JSON"

      - name: Debug needs output
        env:
          # GOOD: toJSON with needs (not secrets)
          NEEDS_JSON: ${{ toJSON(needs) }}
        run: echo "Needs $NEEDS_JSON"

      - name: Debug github context
        env:
          # GOOD: toJSON with github context (not secrets)
          EVENT_JSON: ${{ toJSON(github.event) }}
        run: echo "Event $EVENT_JSON"

  # SAFE: Passing only needed secrets to actions
  safe-action-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Use action with specific secret
        uses: some/action@v1
        with:
          # GOOD: Only pass the specific secret needed
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use another action
        uses: another/action@v2
        with:
          # GOOD: Pass specific secrets by name
          api-key: ${{ secrets.API_KEY }}
          webhook-secret: ${{ secrets.WEBHOOK_SECRET }}

  # SAFE: Reusable workflow with explicit secret inheritance
  call-reusable-workflow:
    uses: ./.github/workflows/reusable.yml
    secrets:
      # GOOD: Explicitly pass only needed secrets
      token: ${{ secrets.GITHUB_TOKEN }}
      npm_token: ${{ secrets.NPM_TOKEN }}
