# This workflow demonstrates excessive secrets exposure vulnerabilities
# These patterns should be detected by the secret-exposure rule
name: Vulnerable Secret Exposure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'

jobs:
  # VULNERABLE: Using toJSON(secrets) exposes ALL secrets
  expose-all-secrets:
    runs-on: ubuntu-latest
    env:
      # BAD: This exposes all repository and organization secrets
      ALL_SECRETS: ${{ toJSON(secrets) }}
    steps:
      - name: Print secrets (DO NOT DO THIS)
        run: |
          echo "Secrets: $ALL_SECRETS"

  # VULNERABLE: Dynamic secret access using format()
  dynamic-format-access:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev, staging, prod]
    steps:
      - name: Get environment-specific secret
        env:
          # BAD: Dynamically constructing secret name
          TOKEN: ${{ secrets[format('GH_PAT_%s', matrix.env)] }}
        run: |
          echo "Token is set"

  # VULNERABLE: Dynamic secret access using variable
  dynamic-variable-access:
    runs-on: ubuntu-latest
    steps:
      - name: Get secret by variable name
        env:
          SECRET_NAME: MY_SECRET
          # BAD: Using variable to access secrets
          SECRET_VALUE: ${{ secrets[env.SECRET_NAME] }}
        run: |
          echo "Secret retrieved"

  # VULNERABLE: Bracket notation with string literal
  bracket-notation:
    runs-on: ubuntu-latest
    steps:
      - name: Get secret with bracket notation
        env:
          # BAD: Using bracket notation instead of dot notation
          MY_TOKEN: ${{ secrets['GITHUB_TOKEN'] }}
        run: |
          echo "Token: $MY_TOKEN"

  # VULNERABLE: toJSON(secrets) in action input
  action-input-exposure:
    runs-on: ubuntu-latest
    steps:
      - name: Use action with all secrets
        uses: some/action@v1
        with:
          # BAD: Passing all secrets to an action
          secrets: ${{ toJSON(secrets) }}

  # VULNERABLE: Dynamic access in run script
  run-script-exposure:
    runs-on: ubuntu-latest
    steps:
      - name: Dynamic secret in script
        run: |
          # BAD: toJSON(secrets) in run script
          echo "${{ toJSON(secrets) }}" > /dev/null
