name: Test ActionList Feature
on: [push]

jobs:
  test-job:
    name: Test Job with Different Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.0"
      
      - name: Untrusted Action Example
        uses: untrusted/action@v1
      
      - name: Suspicious Action Example
        uses: suspicious/repo@main