name: Test ActionList Blacklist Feature
on: [push]

jobs:
  test-job:
    name: Test Job with Blacklisted Actions
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        timeout-minutes: 5
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      - name: Setup Go
        timeout-minutes: 5
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: "1.24.0"
      
      - name: Untrusted Action Example
        timeout-minutes: 5
        uses: untrusted/action@v1
      
      - name: Suspicious Action Example
        timeout-minutes: 5
        uses: suspicious/repo@main