# Vulnerable: Unmasked Secret Exposure
# This workflow demonstrates the security issue where derived secrets are not automatically masked
# See: https://codeql.github.com/codeql-query-help/actions/actions-unmasked-secret-exposure/

name: Unmasked Secret Exposure (Vulnerable)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  vulnerable-job:
    runs-on: ubuntu-latest
    steps:
      # BAD: Extracting values from JSON secrets - derived values are NOT masked
      - name: Use Azure credentials (vulnerable)
        env:
          # These derived values will NOT be masked in logs
          CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
          CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
          TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
        run: |
          echo "Logging in to Azure..."
          # If any of these values are accidentally logged, they will be visible
          az login --service-principal -u "$CLIENT_ID" -p "$CLIENT_SECRET" --tenant "$TENANT_ID"

      # BAD: Using fromJson with index access
      - name: Access config via index (vulnerable)
        env:
          API_KEY: ${{ fromJson(secrets.CONFIG)['apiKey'] }}
        run: |
          curl -H "Authorization: Bearer $API_KEY" https://api.example.com

      # BAD: Nested property access
      - name: Nested access (vulnerable)
        run: |
          echo "Username: ${{ fromJson(secrets.DB_CREDENTIALS).connection.username }}"

      # BAD: Using in action inputs directly
      - name: Deploy with derived secret (vulnerable)
        uses: some/action@v1
        with:
          password: ${{ fromJson(secrets.DEPLOYMENT_CONFIG).password }}

  safe-job:
    runs-on: ubuntu-latest
    steps:
      # GOOD: Use separate secrets for each value
      - name: Use Azure credentials (safe)
        env:
          CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          az login --service-principal -u "$CLIENT_ID" -p "$CLIENT_SECRET" --tenant "$TENANT_ID"

      # GOOD: Direct secret access is properly masked
      - name: Use API key (safe)
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          curl -H "Authorization: Bearer $API_KEY" https://api.example.com

      # GOOD: Manual masking if you must use fromJson
      - name: Manual masking (workaround)
        env:
          DERIVED_SECRET: ${{ fromJson(secrets.CONFIG).apiKey }}
        run: |
          echo "::add-mask::$DERIVED_SECRET"
          # Now the value is masked for subsequent commands
          echo "Using the API key..."
