on:
  pull_request:
    types: [opened, synchronize]

jobs:
  use_pr_title:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Print PR Title
      if: startsWith(github.event.pull_request.title, 'WIP')
      run: echo "Hello!"
