name: Lint
on:
  pull_request:
    paths: ["**.yml", "**.yaml"]
defaults:
  run:
    shell: bash
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint yaml files by yamllint
        run: |
          CONFIG="${RUNNER_TEMP}/.yamllint.yml"
          cat <<EOF >"${CONFIG}"
          extends: default
          rules:
            document-start: disable
            truthy:
              allowed-values: ["true", "false", "on"]
            comments:
              min-spaces-from-content: 1
            braces:
              max-spaces-inside: 1
            line-length:
              max: 150
          EOF
          if [ -e ".yamllint.yml" ]; then
            CONFIG=".yamllint.yml"
          fi
          yamllint --strict --format github --config-file "${CONFIG}" .

      - name: Format yaml files by prettier
        run: |
          npm install prettier@latest
          npx prettier --parser="yaml" --write "**/*.y*ml"
